export const LOGOUT_BUTTON_TEXT = 'Выйти';
export const LOGIN_BUTTON_TEXT = 'Войти';
export const REGISTER_BUTTON_TEXT = 'Регистрация'
export const APP_TITLE = 'Поисковик новостей';
export const ACCESS_TOKEN_STORAGE_KEY = 'token';
export const REFRESH_TOKEN_STORAGE_KEY = 'refresh';
export const USERNAME_STORAGE_KEY = 'username';
export const BASE_URL = 'http://localhost:8080';
export const REGISTER_SUCCESS_MESSAGE = 'Вы успешно зарегистрированы!';